# Julia 服务器 - 通过文件与Claude Code通信
# 启动方式: julia --project=. julia_server.jl

using Revise, Plots, DataFrames, CSV, BenchmarkTools, FFTW, ITensors
using Dates, Random  # 新增 - 用于生成唯一ID和时间戳

# 生成唯一服务器ID
SERVER_ID = "julia_repl_$(getpid())_$(rand(1000:9999))"
println("🤖 Julia 服务器已启动 (ID: $SERVER_ID)")

# 创建通信目录（使用系统临时目录）
COMM_DIR = mktempdir(prefix="julia_repl_")
COMMAND_FILE = joinpath(COMM_DIR, "command.txt")
RESPONSE_FILE = joinpath(COMM_DIR, "response.txt")

# 将配置信息保存到用户主目录的配置文件中
CONFIG_PATH = joinpath(homedir(), ".julia_repl_server_config.jl")

# 转换路径为正斜杠格式，避免Julia解析错误
function normalize_path(path::String)
    return replace(path, "\\" => "/")
end

open(CONFIG_PATH, "w") do f
    println(f, "# Julia REPL Server Configuration")
    println(f, "# Generated by JuliaREPLServer on $(now())")
    println(f, "SERVER_ID = \"$(SERVER_ID)\"")
    println(f, "COMMAND_FILE = \"$(normalize_path(COMMAND_FILE))\"")
    println(f, "RESPONSE_FILE = \"$(normalize_path(RESPONSE_FILE))\"")
    println(f, "COMM_DIR = \"$(normalize_path(COMM_DIR))\"")
    println(f, "START_TIME = \"$(now())\"")
end

println("💾 配置文件已保存: $CONFIG_PATH")

println("📦 所有包已加载")
println("🔄 Revise 热重载已激活")
println("📡 通信目录: $COMM_DIR")
println("🔑 服务器ID: $SERVER_ID")
println("=" ^ 50)

# 注意：由于使用系统临时目录和唯一ID，无需删除旧文件
# mktempdir() 会创建全新的临时目录

# 命令处理函数 - 增强版
function process_command(command)
    try
        # 记录收到的原始命令
        println("📝 收到原始命令: $(repr(command))")

        # 清理命令（移除多余空白）
        cleaned_command = strip(command)
        println("🧹 清理后命令: $(repr(cleaned_command))")

        if startswith(cleaned_command, "include(")
            # 处理文件包含命令
            println("📂 处理文件包含命令")
            eval(Meta.parse(cleaned_command))
            return "✅ 文件加载成功"
        else
            # 尝试执行任意Julia代码
            println("⚡ 执行Julia代码")
            parsed_expr = Meta.parse(cleaned_command)
            println("🔍 解析结果: $(repr(parsed_expr))")

            result = eval(parsed_expr)
            result_str = string(result)
            println("💻 执行结果类型: $(typeof(result))")

            # 限制结果长度，避免过长的响应
            if length(result_str) > 500
                result_str = result_str[1:497] * "..."
            end

            return "✅ 执行成功: $result_str"
        end
    catch e
        # 更详细的错误信息
        error_msg = string(e)
        println("❌ 错误详情: $error_msg")

        # 提供常见错误的解决建议
        if occursin("syntax", lowercase(error_msg))
            error_msg *= "\n💡 建议: 检查Julia语法，特别是引号和括号的匹配"
        elseif occursin("UndefVarError", error_msg)
            error_msg *= "\n💡 建议: 变量未定义，请先定义或加载相应的包"
        elseif occursin("MethodError", error_msg)
            error_msg *= "\n💡 建议: 方法错误，请检查函数参数和类型"
        end

        return "❌ 错误: $error_msg"
    end
end


# 主循环 - 监听命令文件
println("🎯 服务器准备就绪，等待命令...")
println("💡 向 $COMMAND_FILE 写入命令即可执行")

while true
    sleep(0.1)  # 每0.1秒检查一次（从0.5秒优化到0.1秒，提高响应速度）

    if isfile(COMMAND_FILE)
        # 读取命令
        command = strip(read(COMMAND_FILE, String))

        if !isempty(command)
            println("📨 收到命令: $command")

            # 处理命令
            response = process_command(command)
            println("📤 响应: $response")

            # 写入响应
            open(RESPONSE_FILE, "w") do f
                write(f, response)
            end

            # 删除命令文件
            rm(COMMAND_FILE)

            println("✅ 命令处理完成")
        end
    end
end